---
dataset_name: CIFAR10
model_name: densenet40
distributed_algorithm: fed_avg
optimizer_name: SGD
worker_number: 10
batch_size: 32
round: 150
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 5
learning_rate: 0.01
model_kwargs:
    num_classes: 10
dataset_kwargs:
    dataset_type: Vision
    dataset_sampling: dirichlet_split
    classes: [0,1,2,3,4,5,6,7,8,9]
dataset_sampling_kwargs:
  concentration: 0.1
algorithm_kwargs:
    node_sample_percent: 0.7
    node_random_selection: true
graph_worker: false
debug: true
exp_name: "cifar10"
...