---
dataset_name: CIFAR10
model_name: densenet40
distributed_algorithm: graph_fed_avg
optimizer_name: AdamW
optimizer_kwargs:
  betas: [0.9, 0.99]
  eps: 1e-8
  weight_decay: 0.0005
worker_number: 65
batch_size: 64
round: 150
#learning_rate_scheduler_name: CosineAnnealingLR
learning_rate_scheduler_name: ReduceLROnPlateau
learning_rate_scheduler_kwargs:
  mode: "max"
  factor: 0.5
  patience: 5
epoch: 3
learning_rate: 0.0005
model_kwargs:
    num_classes: 10
    keep_model_cache: false
dataset_kwargs:
    dataset_type: Vision
    dataset_sampling: dirichlet_split
    classes: [0,1,2,3,4,5,6,7,8,9]
dataset_sampling_kwargs:
  concentration: 0.5
algorithm_kwargs:
    distribute_init_parameters: True
    node_sample_percent: 0.7
    node_random_selection: false
graph_worker: true
family_number: 4
graph_type: KNN
num_neighbor: 2
threshold: 0.0
laplacian_type: RandomWalk
similarity_function: Gaussian
debug: false
exp_name: "c510"
...