---
dataset_name: PNEUMONIA
model_name: LeNet5
distributed_algorithm: graph_fed_avg
optimizer_name: SGD
worker_number: 2
batch_size: 64
round: 3
learning_rate_scheduler_name: CosineAnnealingLR
epoch: 2
learning_rate: 0.01
dataset_kwargs:
    dataset_type: Medical
    dataset_sampling: iid
algorithm_kwargs:
    node_sample_percent: 0.5
    node_random_selection: False
    random_client_number: 3
graph_worker: True
family_number: 2
graph_type: KNN
num_neighbor: 1
threshold: 0.0
laplacian_type: RandomWalk
similarity_function: Gaussian
debug: True
...