---
dataset_name: CIFAR10
model_name: densenet40
distributed_algorithm: clustered_sampling_algo2
optimizer_name: SGD
optimizer_kwargs:
  momentum: 0.7          # reduce oscillations
  weight_decay: 0.0005   # use real weight decay instead of fake
worker_number: 10
batch_size: 64
round: 5
#learning_rate_scheduler_name: CosineAnnealingLR
learning_rate_scheduler_name: ReduceLROnPlateau
learning_rate_scheduler_kwargs:
  mode: "max"
  factor: 0.5
  patience: 5
epoch: 3
learning_rate: 0.0005
model_kwargs:
    num_classes: 10
    keep_model_cache: false
dataset_kwargs:
    dataset_type: Vision
dataset_sampling: dirichlet_split
dataset_sampling_kwargs:
  concentration: 0.5
algorithm_kwargs:
    node_sample_percent: 0.7
    distribute_init_parameters: True
    node_random_selection: True
graph_worker: false
debug: false
exp_name: "algo2cf"
...